### PR TITLE
Fix compatybility with WPML

### PR DESCRIPTION
**Pull request by kkarpieszuk**
Hi

I reported incompatibility with WPML to @mattyza by email. He asked me to create this as pull request, so I am doing it roght now

### CODE REVIEW

**Comment by RiaanKnoetze** [comment]
@mendezcode - this is one for you to look into :)

**Comment by kkarpieszuk** [comment]
hello, do you have any time estimation for this? :)

**Comment by mendezcode** [comment]
Hello @kkarpieszuk, I've been a bit busy with other things and haven't been able to look into this. I'll take care of this one next week. Apologies for the delay!

**Comment by kkarpieszuk** [comment]
hi @mattyza 

yes, you can do this without switching true/false for suppress_filtrers

just before 

```
$sidebars = get_posts( $args );
```

please add:

```
$current_language = apply_filters('wpml_current_language', false);
do_action('wpml_switch_language', 'all' );
```

and after `get_posts` switch language back with:

```
do_action('wpml_switch_language', $current_language );
```

this way you will also resolve my really stupid error with not checking ICL_LANGUAGE_CODE - replace it with `$current_language`.

**Comment by kkarpieszuk** [comment]
p.s. sorry for really late reply. i came here to ping you with reminderbut I found it is you who is waiting. I didn't get email notification that you are waiting, I am sorry once again

**Comment by kkarpieszuk** [comment]
Hello, I would like to remind you about this one more time :)

**Comment by kkarpieszuk** [comment]
thank you for fixing this! we will test on our side now

**Pull request merged**
