### PR TITLE
Adds option to select "Pages and all their children"

### LINKED ISSUE #24: Condition to apply sidebar to one specific page AND all this children
Hi and thanks for this plugin which saves me a lot of time in many projects.

It would be great to add a feature to create conditions like:
- for the page XXX and all its children

Now if I chose one page in the "Page" condition tab, the sidebar only changes on this page and not for the clidren. It can be done by selecting all subpages but for future pages, its not easy.

Besides, display the hierarchy into this "Page tab" would be great!

Regards

### PR DESCRIPTION
**Pull request by javorszky**
Fixes #24

Applying this patch will:

* add a new tab for Pages and their children
* replace the sidebar on the page and all their children 
* implement an indented list of pages for that display
* apply some code cleanup to the core code (separated the meta box render into more logical chunks)

### CODE REVIEW

**Comment by snrbrnjna** [comment]
@mattyza @javorszky what's the state of this PR?

**Comment by mattyza** [comment]
This needs review from me, @snrbrnjna. I've been a bit behind on reviews here. Hoping to get to this soonest.

**Comment by snrbrnjna** [comment]
ok. thanks for your response @mattyza ! do you think you'll get to it this year?

**Comment by mattyza** [comment]
Yes, @snrbrnjna. :)

**Comment by mattyza** [comment]
Thanks @javorszky !

**Pull request merged**
